Add files via upload
converting A3 stuff with week 8 structure to Mario, just need to figure out epsilon greedy probability distribution properly.

currently running issues running 'training AI' section

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[13], line 15
     13 episode_batch_score = 0
     14 episode_reward = 0
---> 15 agent = DQN_Solver(env)  # create DQN agent
     16 plt.clf()
     17 state = env.reset()

Cell In[12], line 44
     42 def __init__(self, env):
     43     self.memory = ReplayBuffer(env)
---> 44     self.policy_network = Network(env)  # Q
     45     self.target_network = Network(env)  # \hat{Q}
     46     self.target_network.load_state_dict(self.policy_network.state_dict())  # initially set weights of Q to \hat{Q}

Cell In[11], line 15
     11 self.action_space = env.action_space.n          # Getting number of actions in action space
     13 # Defining the layers of the neural network
     14 self.layers = torch.nn.Sequential(
---> 15     torch.nn.Linear(*self.input_shape, FC1_DIMS),   # 
     16     torch.nn.ReLU(),                                # 
     17     torch.nn.Linear(FC1_DIMS, FC2_DIMS),            #
     18     torch.nn.ReLU(),                                #
     19     torch.nn.Linear(FC2_DIMS, self.action_space)    #
...
    295     raise AssertionError(
    296         "libcudart functions unavailable. It looks like you have a broken build?"
    297     )

AssertionError: Torch not compiled with CUDA enabled